import "./components/menu"
import "./components/ex"
import "./components/forms"
import "./components/onload-scripts"
import "./components/search"
import "./components/catalog"
import "./components/stmodal"
import "./components/product-tabs.js"